### ISSUE TITLE
NTR : bacterial treatment by diet

### ISSUE THREAD

**Issue by sabrinatoro** [ybradford/zebrafish-experimental-conditions-ontology#28]
New term name: bacterial treatment by diet

Definition: 
Bacterial treatment where the bacteria are introduced through the diet. 

Parents: 
diet (ZECO:0000112)
bacterial treatment (ZECO:0000106)

Note: 
This term should require a bacteria taxon ID
This term can be used for dient with supplementation of probiotics (e.g. PUB-170720-10)

**Comment by sabrinatoro** [comment]
also needed for ZDB-PUB-170930-5

**Comment by ybradford** [comment]
comment from Sridhar:
The pub is ZDB-PUB-170430-2. They use a probiotic formulation of Streptococcus thermophilus DSM 24731, Bifidobacterium longum DSM 24736, Bifidobacterium breve DSM 24732, Bifidobacterium infantis DSM 24737, Lactobacillus acidophilus DSM 24735, Lactobacillus plantarum DSM 24730, Lactobacillus paracasei DSM 24733, Lactobacillus delbrueckii subs. Bulgaricus DSM 24734. The probiotic strain was mixed into the diet prior to feeding. 

It may be better to have this as a type of diet – probiotic content rather than bacterial treatment and requiring TAXON IDs. Thanks

**Comment by ybradford** [comment]
I previously added bacterial treatment, not sure why it's now showing up in prod. but still have oustanding issue of listing all bacteria in probiotic vs. only having probiotic term

**Comment by ybradford** [comment]
this is available on prod
